name: Run AzDO to GitHub Sync via PS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run:
          ./SynAzDOtoGitHub.psi -GitHubDestinationPAT ${{ secrets.GH_PAT }} - ADOSourcePAT ${{ secrets.AZ_DO_PAT }}